### ISSUE TITLE
Endpoint /graphql returning the 500 Internal Server Error

### ISSUE THREAD

**Issue by yoniakabecky** [upathorg/Backend-in-Node-And-Database#24]

**Comment by justmic007** [comment]
Hi yoni, i have tested both **local and heroku and it works**. How are you using it? I guess you are doing something wrong from your end. Also we will be doing the verification at the resolvers soon. 

BTW, can you screenshot the exact error?

**Comment by yoniakabecky** [comment]
Sorry, this was because of my mistyping.
